
FROM python:3.6.9

MAINTAINER Blaise Mbunga Mputu "mm_blaise@yahoo.fr"

RUN mkdir -p /home/Desktop/streamlit

WORKDIR /home/Desktop/streamlit

RUN pip install streamlit
RUN pip install joblib  

COPY . /home/Desktop/streamlit 

EXPOSE 8501

CMD [ "streamlit", "run", "Streamlit_NLP_Prediction_final.py" ]